---
- name: Check if the Dynatrace installer is provided locally
  local_action:
    module: stat
    path: "{{ playbook_dir }}/roles/{{ dynatrace_agent_role_name }}/files/linux/{{ dynatrace_agent_linux_installer_file_name }}"
  register: dynatrace_agent_installer_file_provided

- include: linux/install-dependencies-apt.yml
  when: ansible_pkg_mgr == "apt"
- include: linux/install-dependencies-yum.yml
  when: ansible_pkg_mgr == "yum"

- include: linux/install-dynatrace-user.yml
- include: linux/install-dynatrace-agent.yml

- include: linux/remove-dependencies-apt.yml
  when: ansible_pkg_mgr == "apt"
- include: linux/remove-dependencies-yum.yml
  when: ansible_pkg_mgr == "yum"
